[package]
name = "randy"
version = "1.3.3"
authors = ["Ian Page Hands <iphands@gmail.com>"]
edition = "2018"

[profile.dev]
opt-level = "s"
debug = 0

[profile.release]
opt-level = 3
codegen-units = 1
panic = 'abort'
lto = true
overflow-checks = false

[features]
default = ["sensors", "nvml-wrapper"]
benchmark = []
timings = []

[[bench]]
name = "proc"
harness = false

[dev-dependencies]
criterion = "0.3"

[dependencies]
glib = "0.10.3"
gio = "0.9.1"
gtk = "0.9.2"
minimal-yaml = "0.1.2"
yaml-rust = "0.4.4"
libc = "0.2"
lazy_static = "1.4.0"
sensors = { version = "0.2.1", optional = true }
nvml-wrapper = { version = "0.6.0", optional = true }
