---
settings:
  background_color: "#000"
  debug: false
  decoration: false
  font-size: x-large
  resizable: false
  timeout: 1

ui:
  - text: SYSTEM
    items:
      - func: hostname
        text: "Hostname:"

      - func: kernel
        text: "Kernel:"

      - func: uptime
        text: "Uptime:"

      - func: cpu_usage
        text: "CPU usage:"
        widget: bar

      - func: cpu_temp_sys
        text: "CPU temp:"

      - func: ram_usage
        text: "RAM usage:"
        widget: bar

      - func: procs
        text: "Running processes:"

      - func: load
        text: "Load:"

      # - func: gpu_temp
      #   text: "GPU Temp:"

  - text: CPUS
    items:
      - type: cpus
        func: cpus
        text: "CPU"

# - text: FILESYSTEM
#   items:
# - text: NETWORKING
#   items:
